name: CrossfitGames
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.10.9
  - numpy=1.24.2
  - pandas=1.5.3
  # - ipykernel=6.15.2
  # - matplotlib=3.1.3
  - requests=2.22.0
  - pip=23.1.0

  - pip:
      - -e.