name: CrossfitGames #This should resemble the repo name
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10.9
  - pandas=1.5.3
  - numpy=1.24.2
  - pyodbc=4.0.35
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pathlib2=2.3.7.post1
  - ipykernel=6.15.2
  - pytest=7.1.3
  - pip=23.0.1
  - requests=2.28.1
  
  - pip:
#This is installs local packages, python packages and functions under /src will be available without listing full path and behave like regular packages.
      - -e .